### ISSUE TITLE
PartyService - getOutParty 환불받고 isFull=false 하도록 구현

### ISSUE THREAD

**Issue by deepredk** [f-lab-edu/ottsharing#129]

**Comment by sue4869** [comment]
@deepredk 파티를 탈퇴하면서 동시에 환불해주는 절차가 괜찮은지 의문이 들어요. 바로 환불이 아닌 탈퇴했다고 표시를 하고 일정 시간이 지난 후(?) 스케줄러를 통해 환불해주는 과정이 맞지 않을까? 하는 생각이 드네요. 멘토링시간에 멘토님께서 비슷한 내용을 말해주셨던 기억도 나고 데드락에 대한 우려도 있어서요. 진홍님은 어떻게 생각하시는지요

**Comment by deepredk** [comment]
@sue4869 
적용하면 좋겠지만 시간이 부족할 것 같습니다 ㅠ
컬럼 추가해야되고, 컬럼 추가에 따라서 내 파티 정보보기 같은쪽 파티 가입여부 인식 로직 수정해줘야 되고, 스케줄러도 짜야되고..

지금으로썬 타협하는게 좋을 거 같다는 생각이에요

**Comment by sue4869** [comment]
네 그럼 지금은 바로 환불로 하고 추후 보완사항으로 남겨둘게요!
